
services:
  app:
    build: .
    container_name: app_test
    volumes:
      - `pwd`/output:/app/target
    networks:
      - grid
    command:
      - clean test
    
  chrome:
    image: selenium/node-chrome:4.9.0-20230421
    container_name: node-chrome
    shm_size: 2gb
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - grid

  edge:
    image: selenium/node-edge:4.9.0-20230421
    container_name: node-edge
    shm_size: 2gb
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - grid

  firefox:
    image: selenium/node-firefox:4.9.0-20230421
    container_name: node-firefox
    shm_size: 2gb
    depends_on:
      selenium-hub:
        condition: service_healthy

    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - grid

  selenium-hub:
    image: selenium/hub:4.9.0-20230421
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - grid
    healthcheck:
      test: curl --fail http://localhost:4444 || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      app:
        condition: service_completed_successfully

networks:
  grid:
    driver: bridge
    name: grid-driver