apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  namespace: keda
  labels:
    name: grid-services
    app: grid

spec:
  type: NodePort
  selector:
      name: hub-pod
      app: grid

  ports:
    - port: 4444
      targetPort: 4444
      nodePort: 31001
      name: port0



  sessionAffinity: None
