apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  namespace: ui-test-job
  name: chrome-scale-deployment
  labels:
    deploymentName: chrome-deployment
spec:
  minReplicaCount: 1
  maxReplicaCount: 8
  scaleTargetRef:
    name: chrome-deployment
  triggers:
    - type: selenium-grid
      metadata:
        url: 'http://selenium-hub.ui-test-job:4444/graphql'
        browserName: 'chrome'
