name: UI Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout of the repo
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Docker cache
      uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true

    - name: setup Hub and nodes and execute the script
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Stop the grid setup
      if: always()
      run: |
        docker-compose -f "docker-compose.yml" down    
   

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
