name: UI Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  id-token: write
  pages: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: checkout of the repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Docker cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: setup Hub and nodes and execute the script
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: wait for the test containers to exit
        run: |
            chmod a+x wait_for_exit.sh 
            ./wait_for_exit.sh app_test
        shell: bash

      - name: Deploy the test output
          uses: peaceiris/actions-gh-pages@v3
          if: github.ref == 'refs/heads/main'
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./output/reports

      - name: Stop the grid setup
        if: always()
        run: |
          docker-compose -f "docker-compose.yml" down  

   